Fix small warning-generating bugs
privacyidea/java-client pull request #43
Opened 2022-11-22 13:26 UTC by lukasmatusiewicz

2022-11-22 13:28 UTC, nilsbehlen requested changes

2022-11-22 13:36 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +    public boolean serviceAccountInaccessible()
Why? That is logic. Logging error when service account is inaccessible. 
If the name should stay, I would change the order to:
`if (serviceAccountAvailable)-> code
else -> error`
For now everywhere is `!` sign to keep it this way.

2022-12-02 07:22 UTC, lukasmatusiewicz commented
Merge Actions PR first

2022-12-15 10:21 UTC, nilsbehlen approved these changes

2022-12-15 10:22 UTC, merged