69 reuse saved jwt auth token until it expire 1
privacyidea/java-client pull request #70
Opened 2024-12-31 11:36 UTC by lukasmatusiewicz

This pull request includes several changes to the `privacyIDEA` project, focusing on refactoring the authentication token retrieval process and improving the JSON parsing logic. The most important changes include the introduction of a scheduled task for automatic token retrieval, modifications to the `JSONParser` class to handle token expiration, and updates to the `PIConstants` class to include new constants.

### Authentication Token Management:

* Added a scheduled task in `PrivacyIDEA` to automatically retrieve and refresh the authentication token (`retrieveAuthToken` method).
* Introduced a new `CountDownLatch` to synchronize token retrieval and added a method to get the token (`getAuthToken`).

### JSON Parsing Enhancements:

* Updated the `extractAuthToken` method in `JSONParser` to return a `LinkedHashMap` with the token and its expiration time.
* Modified the `getItemFromAttributes` method to simplify the retrieval of WebAuthn sign requests.

### Constants Update:

* Added new constants for token expiration and authorization in `PIConstants`.

### Code Cleanup and Refactoring:

* Refactored `AsyncRequestCallable` to use a final `path` variable and removed unnecessary code. [[1]](diffhunk://#diff-745b9a464f2bdbcab04d771cbdac03bdabffc94d39b148d9bfcafb95be0a2897L38-R37) [[2]](diffhunk://#diff-745b9a464f2bdbcab04d771cbdac03bdabffc94d39b148d9bfcafb95be0a2897L66-R66)
* Simplified imports in `JSONParser` and `PIResponse`. [[1]](diffhunk://#diff-dfd1afd5a71fe1f0585172a8d7d31857d59d3d9418cfbe464b96ed4f243f0cb9L21-R21) [[2]](diffhunk://#diff-18937acf40a6322a24b14990029ebba1940ccc9629d4a87dab011561159c3f96L26-R27)

### Test Adjustments:

* All tests updated!

2025-01-30 11:38 UTC, nilsbehlen requested changes

2025-01-30 11:38 UTC, nilsbehlen commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        if (this.parser.parsePIResponse(response) != null && this.parser.parsePIResponse(response).value)
do not call `parsePIResponse` twice

2025-01-30 11:38 UTC, nilsbehlen commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        String response = runRequestAsync(ENDPOINT_AUTH, serviceAccountParam(), Collections.emptyMap(), false, POST);
latch needs to be set again for this to work more than once?

2025-02-10 08:22 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        if (this.parser.parsePIResponse(response) != null && this.parser.parsePIResponse(response).value)
right
[faf235b](https://github.com/privacyidea/java-client/pull/70/commits/faf235b40b1d76be06c097ad3f717e26213bc47b)

2025-02-10 12:45 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        String response = runRequestAsync(ENDPOINT_AUTH, serviceAccountParam(), Collections.emptyMap(), false, POST);
[9f77a94](https://github.com/privacyidea/java-client/pull/70/commits/9f77a940dbe44747fdbea5e9b032a0a3782d15fb)

2025-02-10 15:06 UTC, nilsbehlen commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        authTokenLatch = new CountDownLatch(1);
i think this should be at the start of the function

2025-02-11 10:21 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        authTokenLatch = new CountDownLatch(1);
By the first time there is already one created at the start. After use it prepares authTokenLatch for another use. Is it wrong?

2025-02-12 11:30 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/PrivacyIDEA.java
> +        authTokenLatch = new CountDownLatch(1);
[81b52af](https://github.com/privacyidea/java-client/pull/70/commits/81b52af0309185c5e8710e1e24f5871a44cd34e9)

2025-02-13 14:00 UTC, nilsbehlen approved these changes

2025-03-26 09:36 UTC, merged